### ISSUE TITLE
Weird error when running on systemd

### ISSUE THREAD

**Issue by Fastidious** [lus/pasty#36] opened 2022-01-29 00:03 UTC
When I run pasty from the command line, and use Caddy to proxy to it, it works fine, no issues. Of course, I want to run it with `systemd`. This is my `systemd` file:
```
[Unit]
Description=Pastie
After=network.target

[Service]
Type=simple
Restart=on-failure
RestartSec=10
StartLimitBurst=5
StartLimitInterval=100
User=www-data
Group=www-data
ExecStart=/usr/local/bin/pasty
EnvironmentFile=/usr/local/etc/pasty/.env

[Install]
WantedBy=multi-user.target
```
Pasty will start fine, and run, but when I try accessing it, I get `Cannot open requested path`. Any idea of what could be happening?

**Comment by lus** [comment] 2022-01-29 00:06
The issue there is that pasty serves the web frontend by reading the `./web/` folder which does not exist in your environment.

**Comment by Fastidious** [comment] 2022-01-29 00:07
It does. See `EnvironmentFile`.

**Comment by Fastidious** [comment] 2022-01-29 00:08
There is also a `.env` where pasty is as well. Same result.

**Comment by lus** [comment] 2022-01-29 00:09
I am not talking about the `.env` file, the issue is the `./web/` directory which has to contain the web frontend.
I wrote that part when go did not have static file embedding so I had to accept that trade-off.

**Comment by Fastidious** [comment] 2022-01-29 00:10
Oh! Hmm, so pasty is not fully self-contained, it requires the `web` directory? How can I achieve this? I even change paths, like this:
```
[Unit]
Description=Pastie
After=network.target

[Service]
Type=simple
Restart=on-failure
RestartSec=10
StartLimitBurst=5
StartLimitInterval=100
User=www-data
Group=www-data
ExecStart=/usr/local/src/pasty/pasty
EnvironmentFile=/usr/local/src/pasty/.env

[Install]
WantedBy=multi-user.target
```
Which points to pasty on the repo itself, where the other files are, as still the same.

**Comment by lus** [comment] 2022-01-29 00:12
Yes, that's a bad solution, but it was not possible otherwise when I wrote that part of pasty.
I opened #37 which addresses this. I will take a look into this now and notify you here if I can achieve a solution.
That may take several minutes, an hour or a day, I'm not sure how complex that will be.

**Comment by lus** [comment] 2022-01-29 00:33
Further status updates will be posted to the just-linked issue.
As it will take some time to embed the frontend into the binary I pushed a temporary workaround which is messy but could help you.
You can build pasty using this command:

```bash
go build \
        -o pasty \
        -ldflags "\
            -X github.com/lus/pasty/internal/static.TempFrontendPath=/your/frontend/path" \
        ./cmd/pasty/main.go
```

If you use the binary that gets built by that command, pasty will use `/your/frontend/path` instead of `./web` to load the frontend. You can use this solution to define an absolute path to the frontend directory.

This is **not** meant to be a long-term solution but could help you to continue with your setup so that you are not stuck until I manage to make the binary fully self-contained.

Please let me know if this helps you or if you need any further support from my side.

**Comment by Fastidious** [comment] 2022-01-29 02:35
I tried this and couldn't get it to work. This is what I used:
```
go build \
        -o pasty \
        -ldflags "\
            -X github.com/lus/pasty/internal/static.TempFrontendPath=/usr/local/pasty/web" \
        ./cmd/pasty/main.go
```
Where `/usr/local/pasty/web` contains the actual (original) frontend. Still getting the same error.

**Comment by Fastidious** [comment] 2022-01-29 02:40
Could I suggest, once you achieve the long-term solution for this, to pack everything in it that is currently being pulled from CDNs (I counted four items)? Thanks again!

**Comment by lus** [comment] 2022-01-29 02:43
Yes, I'll open a separate issue for that. I'll close this one then. If there are any further questions feel free to open another one!

**Closed by lus** 2022-01-29 02:43 UTC
Labels: area/backend
